# Generated by Django 4.1 on 2022-09-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentidos', '0002_opinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='calification',
            field=models.IntegerField(),
        ),
    ]
