# Generated by Django 4.1 on 2022-09-10 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentidos', '0003_alter_opinion_calification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=7)),
            ],
        ),
    ]
