# Generated by Django 4.1 on 2022-09-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentidos", "0007_alter_usuario_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="user_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
