# Generated by Django 4.1 on 2022-10-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentidos", "0008_reserva_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="cancelado",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
