# Generated by Django 4.1 on 2022-10-18 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentidos", "0009_reserva_cancelado"),
    ]

    operations = [
        migrations.CreateModel(
            name="Personal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Ma", "Maitre"),
                            ("P", "Propietario"),
                            ("Mz", "Mozo"),
                            ("C", "Cajero"),
                        ],
                        max_length=7,
                    ),
                ),
            ],
        ),
    ]
